# 公共配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
spring:
  application:
    name: aibot-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aibot
    username: root
    password: root
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  task:
    execution:
      pool:
        core-size: 30
        max-size: 200
        queue-capacity: 1000
    #password: 123456
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory

  # 微信开放平台
  # todo 需替换配置
  open:
    appId: wx13b044f1a6f28508
    appSecret: 65f20e3d20de29e7f1739624a8eceb53
  #小程序微信
  miniapp:
    appId: wx13b044f1a6f28508  # 小程序微信公众平台appId
    secret: 65f20e3d20de29e7f1739624a8eceb53  # 小程序微信公众平台api秘钥
# Sa-Token配置
sa-token:
  # token名称（同时也是 cookie 名称）
  token-name: satoken
  # token有效期（单位：秒）默认30天
  timeout: 2592000
  # token最低活跃频率（单位：秒）
  active-timeout: -1
  # 是否允许同一账号多地同时登录
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true


# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.juzipi.springbootinit.controller

# AI 知识库
Ai:
  anythingllm:
    accesskey: N0H5QSQ-JJD4SRE-HB88394-WNZ0GMC
    workspaceId: dev1
    apiAddress: http://juzipi.natapp1.cc/api/v1/openai/chat/completions
    temperature: 0.7


forbidden:
  initial-words:
    - 暴力
    - 色情
    - 诈骗
    - 赌博
    - 毒品
    - 习近平